/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davicres' at '01/04/16 11:31' with Gradle 2.12
 *
 * @author davicres, @date 01/04/16 11:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
